### ISSUE TITLE
Feature requests 

### ISSUE THREAD

**Issue by Rickyrvxlovet** [Diphen-Hydramine/kavimo-download#1]
add batch downloads

**Comment by Diphen-Hydramine** [comment]
you could technically use a python script to automatic calling of the app

example:
https://stackoverflow.com/questions/28032457/send-input-to-command-line-prompt-from-python-program

until I create the feature in a few days from now

**Comment by Diphen-Hydramine** [comment]
download latest version and read the batch download section in the README page
