### ISSUE TITLE
اجرا کردن برنامه تحت ربات تلگرام

### ISSUE THREAD

**Issue by danialz84** [Diphen-Hydramine/kavimo-download#10]
امکانش هست این برنامه را با زبان پایتون و در ربات تلگرام ران کرد؟!
یعنی لینک بدن به ربات فایل را از سرور دانلود کنه بعد هم برام بفرسته

**Comment by Diphen-Hydramine** [comment]
ربات تلگرامی به صورت عادی فایل بزرگتر از 50MB رو ارسال نمیکنه.
برای ارسال فایل های بزرگتر تا 2GB لازم هست [اپلیکیشن ](https://core.telegram.org/api/obtaining_api_id)یا [لوکال سرور](https://github.com/tdlib/telegram-bot-api) طراحی بشه که من تا به حال موفق به انجامش نشدم


قابلیت انجام داره اما به دلیل سختی و هزینه های سرور برنامه ای براش نداریم فعلا
