### ISSUE TITLE
خطا

### ISSUE THREAD

**Issue by mohammadqwerty-asd** [Diphen-Hydramine/kavimo-download#11]
سلام
بعضی مواقع با این خطا روبرو میشه
'tokio-runtime-worker' panicked at src\video\mod.rs:365:52:
called Result::unwrap() on an Err value: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

**Comment by Diphen-Hydramine** [comment]
لینک ویدئو رو برام بفرست لطفا
احتمالا اسم ویدئو خیلی طولانی هست باعث این اتفاق میشه.

**Comment by mohammadqwerty-asd** [comment]
توی دانلود دسته ای اینطوری شد
هرکاری کرد همون خطا رو داد
لطفا اگر میشه رفعش کن دمت گرم

**Comment by mohammadqwerty-asd** [comment]
نمیدونم چرا این خطا رو میده
قبلا همین اتفاق افتاده بود بعد یه مدتی خودمم زدم دانلود شد
ولی این اواخر زیاد شده

**Comment by mohammadqwerty-asd** [comment]
قشنگ دانلود میشه ها ولی یه دفعه این خطا میاد

**Comment by Diphen-Hydramine** [comment]
ورژن v1.3.1 رو استفاده بکن احتمالا دیگه ارور نمیده اما اگر باز هم اتفاق افتاد اررور واضح تری میده که بهتر بشه چکش کرد
تا اون موقع این رو میبندم

**Comment by Diphen-Hydramine** [comment]
لینک ورژن v1.3.1

https://github.com/Diphen-Hydramine/kavimo-download/releases/download/v1.3.1/kavimo-download.exe

**Comment by mohammadqwerty-asd** [comment]
thread 'tokio-runtime-worker' panicked at src\video\mod.rs:359:39:
called Result::unwrap() on an Err value: reqwest::Error { kind: Body, source: hyper::Error(Body, Custom { kind: UnexpectedEof, error: IncompleteBody }) }
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

سلام
اینبار این ارور رو داد
البته بعدش دوباره زدم از همونجا که متوقف شد شروع به دانلود کرد
فقط گفتم که بدونی

**Comment by Diphen-Hydramine** [comment]
الان تازه دیدم این پیام رو گذاشتی
چیز خاصی نیست معمولا بخاطر اختلات اینترنتی و vpn و اینا اینجوری میشه راه حل خاصی نداره فقط میشه دوباره تلاش کرد تا اوکی بشه 
میشه همین رو به کدش اضافه بکنم ولی تنبلیم میاد
