### ISSUE TITLE
درخواست ویژگی

### ISSUE THREAD

**Issue by mohammadqwerty-asd** [Diphen-Hydramine/kavimo-download#12]
ممکنه در کنار کیفیت در دانلود دسته، انتخاب نام هم وجود داشته باشه؟
مثلا
https://stream.kavimo.com/fqvpum2y8drk/embed  1 480
https://stream.kavimo.com/fqvpum2y8drk/embed  2
بالایی کیفیت 480 و اسمش 1 هست
و پایینی طبق معمول کیفیتش بالاترین کیفیت موجوده و اسمش 2 هست
این برای مواردی استفاده میشه که ویدیهای زیادی در حال دانلود هستن و اسمشون نظم و ترتیب خاصی نداره
این کار باعث میشه از قبل نظم ایجاد کرد
و جای اسم هم خالی باشه به این معنی باشه که اسم اصلی خود ویدیو استفاده بشه

**Comment by mohammadqwerty-asd** [comment]
البته دیگ زیادی درخواستهام زیاد شده(:

**Comment by Diphen-Hydramine** [comment]
کار پیچیده ایه
ترجیح میدم تا جایی که ممکن هست جوری طراحی بشه که کاربر های بیشتری بتونن باهاش ارتباط بگیرن
شاید توی ورژن های بعدی gui اضافه بکنم بهش حتی

ولی طرحی که ارائه کردی گیج کننده اس
ساده ترین ابهامش اینه:
`https://stream.kavimo.com/fqvpum2y8drk/embed 480`

1) ویدئو رو دانلود بکن و اسمش رو بزار 480
2) ویدئو رو با کیفیت 480 دانلود بکن و اسمش اسم اصلی ویدئو باشه

**Comment by Diphen-Hydramine** [comment]
فرضا اگر اسم ویدئو شامل space باشه بدتر هم میشه
بعد باید یجوری محل اسم گزاری با پرانتز یا گیومه مشخص بشه که احتمالا یه کلاس آموزشی کامل نیاز داره

`https://stream.kavimo.com/fqvpum2y8drk/embed "video_name" 480`
`https://stream.kavimo.com/fqvpum2y8drk/embed (video_name) 480`

حالا اگر همین رو فارسی بنویسی:

`https://stream.kavimo.com/fqvpum2y8drk/embed "نام ویدئو" 480`
`https://stream.kavimo.com/fqvpum2y8drk/embed (نام ویدئو) 480`

بعدش مشکل اینکه که اگر بخوام داخل اسم پرانتز داشته باشم چی؟ الی آخر همینجوری به صورت زنجیره ای میافتن پشت هم

**Comment by mohammadqwerty-asd** [comment]
اره خوب ممکنه اونطوری مشکل بشه
ولی من برای خودم گفتم که من اسم ویدیوهارو همیشه از1 میذارم تا مثلا 100 که هیچوقت به 480 نمیرسه
پرانتز و ... که اصلا نمیذارم
من زیاد سر در نمیارم ازین برنامه نویسی ها و مشکلاتش(:
کلا نمیشه آخرین ورژن که زدیو این آپشن رو فقط برای من بزنید؟
کلا من اینطوری توی دانلود دسته ای استفاده میکنم
فرض کن لینکها متفاوتن
https://stream.bonyani.ir/afjun6ll9gqj/embed 1
https://stream.bonyani.ir/afjun6ll9gqj/embed 2
https://stream.bonyani.ir/afjun6ll9gqj/embed 3
...
https://stream.bonyani.ir/afjun6ll9gqj/embed 100
همه هم کیفیت 1080 هستن من کیفیتو عوض نمیکنم کلا بالاترین رو همیشه استفاده میکنم
ولی اگر نمیشه که اصلا فدای سرت

**Comment by Diphen-Hydramine** [comment]
مینویسم توی کار هام بعدا یجوری انجامش میدم

**Comment by mohammadqwerty-asd** [comment]
دمت گرم
