### ISSUE TITLE
زمانبندی دانلود

### ISSUE THREAD

**Issue by danialz84** [Diphen-Hydramine/kavimo-download#13]
امکانش هست که که دانلود ها را زمانبندیش کرد 
مثل idm؟!
شدیدا نیازه...

**Comment by Diphen-Hydramine** [comment]
برای اینترنت نامحدود شبانه ؟

**Comment by danialz84** [comment]
بله

**Comment by Diphen-Hydramine** [comment]
تا بعد از عید نیستم بعدش چک میکنم

**Comment by danialz84** [comment]
برگشتید؟!

> تا بعد از عید نیستم بعدش چک میکنم

**Comment by Diphen-Hydramine** [comment]
این بخش رو ببین و ورژن جدید رو دانلود بکن 
https://github.com/Diphen-Hydramine/kavimo-download/tree/latest?tab=readme-ov-file#timer

اگر سوالی نیست issue رو هم ببند
