### ISSUE TITLE
Biomaze Error

### ISSUE THREAD

**Issue by lamirsk** [Diphen-Hydramine/kavimo-download#15]
Bro Maz broke down again and gives an error when downloading

**Comment by Diphen-Hydramine** [comment]
it's working fine for 
https://stream.biomaze.ir/b6tnnbbopku1/iframe


can you send the error causing link

**Comment by lamirsk** [comment]
yes check this https://stream.biomaze.ir/zujopcmicskf

**Comment by Diphen-Hydramine** [comment]
I downloaded it just fine

**Comment by Diphen-Hydramine** [comment]
would you try again and see the error still persists in the newer version
if so could you please send a screen shot of it

**Comment by lamirsk** [comment]
![Screenshot (59)](https://github.com/Diphen-Hydramine/kavimo-download/assets/75976546/3a445bd9-f3b9-488f-ac2e-2b4b08fa3321)

**Comment by Diphen-Hydramine** [comment]
does it occur on every link or is it specific to some links ?
I'm pretty sure you are not using the latest version could you try that also.
and check if foreign IP is the root cause or not

**Comment by Diphen-Hydramine** [comment]
I cannot reproduce the issue on my system so it's a hard one to debug

**Comment by lamirsk** [comment]
The latest version is the one I use

**Comment by Diphen-Hydramine** [comment]
I'm pretty sure you are wrong about using the latest version

try:
> kavimo-download.exe -V

and verify that it's 1.4.0

**Comment by Diphen-Hydramine** [comment]
Also there was two other things you had to check 

> does it occur on every link or is it specific to some links ? I'm pretty sure you are not using the latest version could you try that also. and check if foreign IP is the root cause or not
