### ISSUE TITLE
Seeking Successor for Project

### ISSUE THREAD

**Issue by Diphen-Hydramine** [Diphen-Hydramine/kavimo-download#17]
I'm looking for someone to take over my project. 
Due to personal reasons, I'm unable to continue its development. If you're interested in becoming the new maintainer and have the expertise, please reach out. 
Thanks!

**Comment by lamirsk** [comment]
Bro if you can bypass SpotPlayer I really need it

**Comment by Diphen-Hydramine** [comment]
> Bro if you can bypass SpotPlayer I really need it

Despite having no excess time breaking spotplayer seems kinda fun
could you provide me with a working license and video file please

**Comment by Diphen-Hydramine** [comment]
I've been away from internet for so long I don't even know if this project still works

**Comment by Mohammad1384qshmi** [comment]
بنده میتونم اگه مایل باشین و توضیحات بدین پروژه رو دست،بگیرم یا حامی پروژه باشم

**Comment by Bee-7** [comment]
من هم میتونم کمک کنم میتونیم با هم در تماس باشیم

**Comment by Mohammad1384qshmi** [comment]
ایدی از تلگرام برای بنده بزارین
