### ISSUE TITLE
تایمر کار نمی کنه

### ISSUE THREAD

**Issue by danialz84** [Diphen-Hydramine/kavimo-download#19]
وقتی من تایمر می زار مثلا از 1 شب تا 7 صبح  این خطا رو میده Exited the time range specified stopping the program و کار نمیکنه

**Comment by Diphen-Hydramine** [comment]
درسته قسمت تایم شروع جوری نیست که صبر بکنه تا زمانش برسه بعد ادامه بده.
اونجوری منطقی تره 100 درصد، یه ورژن جدید میدم بزودی

**Comment by Diphen-Hydramine** [comment]
یه ورژن جدید گذاشتم 1.4.1 اون رو دانلود بکنی مشکلش حل میشه

**Comment by Rahim980** [comment]
متاسفانه کاویمو آپدیت شده و برنامه از کار افتاده
