### ISSUE TITLE
آموزش دانلود از کاویمو

### ISSUE THREAD

**Issue by Esexxxo13** [Diphen-Hydramine/kavimo-download#20]
سلام اگه امکانش هست آموزش دانلود از سایت کاویمو رو به من یاد بدید.آیدی تلگرامم @Ehsanghagha13

**Comment by Diphen-Hydramine** [comment]
@lamirsk

**Comment by Diphen-Hydramine** [comment]
من برام ممکن نیست در تلگرام با کسی در ارتباط باشم در بین کسانی که این رو میبینن هرکسی تونست کمک رسانی بکنه
