### ISSUE TITLE
آپدیت کاویمو

### ISSUE THREAD

**Issue by Rahim980** [Diphen-Hydramine/kavimo-download#22]
متاسفانه امروز کاویمو آپدیت شده و برنامه از کار افتاده،شما هم آپدیت میدین؟

**Comment by Diphen-Hydramine** [comment]
کاویمو رو چک کردم 
آپدیتی که دادن یه بروزسانی کامله و انگار خیلی قسمت هارو از اول نوشتن این برای من یعنی که نمیتونم با تغییر دادن یه پارامتر کوچیک آپدیتی بدم که کار بکنه و بیشتر شبیه اینه که برنامه باید از اول نوشته بشه که خیلی زمانبر تر هست (تقریبا ۴۰ الی ۸۰ ساعت)

من همونجوری که توی آخرین پیامم گذاشتم دنبال کسیم که بتونه این پروژه رو به سرپرستی بگیره و دیگه علاقه ای به ادامه دادنش ندارم.
فعلا آپدیت جدیدی نمیزارم 
شاید اما تا اواخر تابستون اگر کسی پیدا نشد که این کار رو انجام بده یه آپدیت جدید گذاشتم که قولی بابتش نمیدم.


درحال حاضر این پروژه maintainer ندارد.

**Comment by mohammadqwerty-asd** [comment]
داداش میتونی زودترم بذاری لطفا تا اونموقع میپرونن همشو(:

**Comment by Mohammad1384qshmi** [comment]
بنده میتونم اگه مایل باشین و توضیحات بدین پروژه رو دست،بگیرم یا حامی پروژه باشم

**Comment by Esexxxo13** [comment]
داداش ببین اگه میتونی ی کار کن خیلی نیازه

**Comment by mehrshadking2** [comment]
سلام داداش خوبی میگم دیگه آپدیت نمیشه؟کلا؟واقعا ابزاری که نیازه

**Comment by mehrshadking2** [comment]
داداش من میتونم به عهده بگیرم چجوری باهات خصوصی تماس بگیرم؟

**Comment by Diphen-Hydramine** [comment]
> داداش من میتونم به عهده بگیرم چجوری باهات خصوصی تماس بگیرم؟


من فعلا تا اطلاع ثانوی در دسترس نیستم
اگر میتونی آپدیت اضافه بکنی PR بزن روی پروژه

**Comment by Diphen-Hydramine** [comment]
آپدیتی که خودم بدم حدود مرداد یا شهریور میشه

**Comment by mehrshadking2** [comment]
> > داداش من میتونم به عهده بگیرم چجوری باهات خصوصی تماس بگیرم؟
> 
> من فعلا تا اطلاع ثانوی در دسترس نیستم اگر میتونی آپدیت اضافه بکنی PR بزن روی پروژه



> آپدیتی که خودم بدم حدود مرداد یا شهریور میشه

الان خودت آپدیت میدی ؟

**Comment by Rahim980** [comment]
دیفن هیدارمین عزیز،واقعا این آپدیت برامون خیلی مهم و حیاتیه،میدونیم زمان بر و سخته ولی یکاریش بکن

**Comment by Diphen-Hydramine** [comment]
@mehrshadking2 
اگر میتونی آپدیت بده
حرف بیخودی نزن الکی
دفعه بعدی issue رو الکی پر کنی میندزامت بیرون از repo 

لازمم نیست با کسی تماس بگیری ما امثال شما رو نشناسیم باید بریم بمیریم

**Comment by mehrshadking2** [comment]
> @mehrshadking2 اگر میتونی آپدیت بده حرف بیخودی نزن الکی دفعه بعدی issue رو الکی پر کنی میندزامت بیرون از repo
> 
> لازمم نیست با کسی تماس بگیری ما امثال شما رو نشناسیم باید بریم بمیریم

والا قصدم بد نیست و خیره من خواستم کمک کنم ولی متوجه نشدم گفتی آپدیت خودم میدم بازم عذر میخوام

**Comment by Shahnamakviko** [comment]
درود خدمت شما بزرگوار قرض از مزاحمت خواستم بدونم آیا فایل دانلود آپدیت جدید خواهد داشت یا خیر،؟

**Comment by ashegh8** [comment]
> درود خدمت شما بزرگوار قرض از مزاحمت خواستم بدونم آیا فایل دانلود آپدیت جدید خواهد داشت یا خیر،؟

فکر نکنم با این وضعیت آپدیتی در کار باشه

**Comment by Shahnamakviko** [comment]
> > درود خدمت شما بزرگوار قرض از مزاحمت خواستم بدونم آیا فایل دانلود آپدیت جدید خواهد داشت یا خیر،؟
> 
> فکر نکنم با این وضعیت آپدیتی در کار باشه

مشکل اینه همش آپدیت ممکنه بده و باید سورسی نوشته بشه که در هر آپدیتی بتونه دانلود کنه

**Comment by Shahnamakviko** [comment]
و واقعا سخته فایل ران بهتر عمل میکنه امیدوارم دوباره آپدیت کنن فایل ران رو چون بسیاری از احتیاج ها رو رفع میکنه

**Comment by Shahnamakviko** [comment]
> @mehrshadking2 اگر میتونی آپدیت بده حرف بیخودی نزن الکی دفعه بعدی issue رو الکی پر کنی میندزامت بیرون از repo
> 
> لازمم نیست با کسی تماس بگیری ما امثال شما رو نشناسیم باید بریم بمیریم
اول که ببخشید مزاحمتون میشم
حالا شما خودتون دیگه فایل ران رو اوکی نمیکنید؟

**Comment by Shahnamakviko** [comment]
> @mehrshadking2 اگر میتونی آپدیت بده حرف بیخودی نزن الکی دفعه بعدی issue رو الکی پر کنی میندزامت بیرون از repo
> 
> لازمم نیست با کسی تماس بگیری ما امثال شما رو نشناسیم باید بریم بمیریم

سلامی دوباره میخواستم خدمت شما عرض کنم روش دیگه ای برای دانلود از کاویمو هست؟بنده اشتراک یک سایت خریداری کردم که نمیتونم سیو کنم

**Comment by Shahnamakviko** [comment]
خیلی دیدم که با همین وضع فیلم ها رو دانلود میکنن اما روش دانلودشون مشخص نیست!

**Comment by ashegh8** [comment]
> خیلی دیدم که با همین وضع فیلم ها رو دانلود میکنن اما روش دانلودشون مشخص نیست!
امکانش هست بگید از کجا دید دانلود میکنن؟

**Comment by Diphen-Hydramine** [comment]
فکر کنم یجورایی حل شده دیگه
این فیلم آموزشیشه
نسبت به قبل دردسرش بیشتره ولی واسه یه راه حل سرعتی خوبه

https://mega.nz/file/92lR2TZL#tc7fu_G4kSDAD8MSSSLsRrCqG8ZJeFoTaWlzS3j1oIU

**Comment by Diphen-Hydramine** [comment]
احتمالا خیلیا به مشکل میخورن سر پیدا کردن اون متنی که باید داخل برنامه بزارن هرکس گیر کرد همینجا سوالش رو بپرسه

**Comment by AidinShekari** [comment]
> احتمالا خیلیا به مشکل میخورن سر پیدا کردن اون متنی که باید داخل برنامه بزارن هرکس گیر کرد همینجا سوالش رو بپرسه

انجام میدم اخرش همچین حالتی میشه #EXTINF:4,
https://as-ir-teh-at-n5.c-d-n.io/jt-944…"

**Comment by Shahnamakviko** [comment]
> فکر کنم یجورایی حل شده دیگه این فیلم آموزشیشه نسبت به قبل دردسرش بیشتره ولی واسه یه راه حل سرعتی خوبه
> 
> https://mega.nz/file/92lR2TZL#tc7fu_G4kSDAD8MSSSLsRrCqG8ZJeFoTaWlzS3j1oIU

سلام امتحان کردیم فقط رو ماز جوابگوعه و مؤسساتی که رو صفحات جدید باز می‌شوند مثل آلفا اسکول کرمی جوابگو نیست اون مدل رو لطفا راهنمایی کنید که ویدئو فقط در صفحه جدید باز میشه

**Comment by ashegh8** [comment]
> احتمالا خیلیا به مشکل میخورن سر پیدا کردن اون متنی که باید داخل برنامه بزارن هرکس گیر کرد همینجا سوالش رو بپرسه

سلام و عرض خسته نباشید خدمتتون
چطور میشه کیفیت رو انتخاب کرد؟
خودش با کیفیت پایین ویدیو رو دانلود میکنه

**Comment by mohammadqwerty-asd** [comment]
فکر کنم کیفیت رو قبل از پیدا کردن اون متن توی خود ویدیو تنظیم کنیم مثلا اگر 720 میخواید توی ویدیو 720 بذاریم بعد اون متنو پیدا کنیم
این حدس منه هنوز خودم انجام ندادم

**Comment by Diphen-Hydramine** [comment]
> فکر کنم کیفیت رو قبل از پیدا کردن اون متن توی خود ویدیو تنظیم کنیم مثلا اگر 720 میخواید توی ویدیو 720 بذاریم بعد اون متنو پیدا کنیم این حدس منه هنوز خودم انجام ندادم

درسته برای انتخاب کیفیت میشه از این روش استفاده کرد

**Comment by Diphen-Hydramine** [comment]
> > فکر کنم یجورایی حل شده دیگه این فیلم آموزشیشه نسبت به قبل دردسرش بیشتره ولی واسه یه راه حل سرعتی خوبه
> > https://mega.nz/file/92lR2TZL#tc7fu_G4kSDAD8MSSSLsRrCqG8ZJeFoTaWlzS3j1oIU
> 
> سلام امتحان کردیم فقط رو ماز جوابگوعه و مؤسساتی که رو صفحات جدید باز می‌شوند مثل آلفا اسکول کرمی جوابگو نیست اون مدل رو لطفا راهنمایی کنید که ویدئو فقط در صفحه جدید باز میشه



یک موردی که نمیتونی انجام بدی رو لینکش رو برام بفرست که تست بکنم

**Comment by Shahnamakviko** [comment]
> > > فکر کنم یجورایی حل شده دیگه این فیلم آموزشیشه نسبت به قبل دردسرش بیشتره ولی واسه یه راه حل سرعتی خوبه
> > > https://mega.nz/file/92lR2TZL#tc7fu_G4kSDAD8MSSSLsRrCqG8ZJeFoTaWlzS3j1oIU
> > 
> > 
> > سلام امتحان کردیم فقط رو ماز جوابگوعه و مؤسساتی که رو صفحات جدید باز می‌شوند مثل آلفا اسکول کرمی جوابگو نیست اون مدل رو لطفا راهنمایی کنید که ویدئو فقط در صفحه جدید باز میشه
> 
> یک موردی که نمیتونی انجام بدی رو لینکش رو برام بفرست که تست بکنم

پنل هست لینک کافیه؟باز نمیشه که لینکش

**Comment by Shahnamakviko** [comment]
> > > فکر کنم یجورایی حل شده دیگه این فیلم آموزشیشه نسبت به قبل دردسرش بیشتره ولی واسه یه راه حل سرعتی خوبه
> > > https://mega.nz/file/92lR2TZL#tc7fu_G4kSDAD8MSSSLsRrCqG8ZJeFoTaWlzS3j1oIU
> > 
> > 
> > سلام امتحان کردیم فقط رو ماز جوابگوعه و مؤسساتی که رو صفحات جدید باز می‌شوند مثل آلفا اسکول کرمی جوابگو نیست اون مدل رو لطفا راهنمایی کنید که ویدئو فقط در صفحه جدید باز میشه
> 
> یک موردی که نمیتونی انجام بدی رو لینکش رو برام بفرست که تست بکنم

وقتی که میزنی فیلم در صفحه جدید باز میشه و میگم فیلم آموزشی خیلی ریزه نوشته ها میشه زوم کرد؟

**Comment by Diphen-Hydramine** [comment]
@Shahnamakviko 

مراحل رو از اونجایی که devtools رو باز میکنی 
(پنل سمت راست صفحه)
قبل از استارت تماشای ویدئو دوباره انجام بده 

اگر میتونی که کلیپ توضیحات یا مشابه اش رو برام پیدا بکن که خودم تست بکنم

از بابت کیفیت ویدئو کاری از دستم بر نمیاد اگر کس دیگه ای دوباره کلیپ بگیره و منتشر بکنه عالیه

**Comment by Shahnamakviko** [comment]
> > احتمالا خیلیا به مشکل میخورن سر پیدا کردن اون متنی که باید داخل برنامه بزارن هرکس گیر کرد همینجا سوالش رو بپرسه
> 
> سلام و عرض خسته نباشید خدمتتون چطور میشه کیفیت رو انتخاب کرد؟ خودش با کیفیت پایین ویدیو رو دانلود میکنه

شما میتونی ویدئو توضیحات رو برای بنده در پلتفرم تلگرام بفرستی؟

**Comment by Shahnamakviko** [comment]
> @Shahnamakviko
> 
> مراحل رو از اونجایی که devtools رو باز میکنی (پنل سمت راست صفحه) قبل از استارت تماشای ویدئو دوباره انجام بده
> 
> اگر میتونی که کلیپ توضیحات یا مشابه اش رو برام پیدا بکن که خودم تست بکنم
> 
> از بابت کیفیت ویدئو کاری از دستم بر نمیاد اگر کس دیگه ای دوباره کلیپ بگیره و منتشر بکنه عالیه

مشکل اینه فقط ویدئو در تب جدید باز میشه

**Comment by Shahnamakviko** [comment]
> آیدیت رو بزار

@tryface1 مچکرم از لطفت

**Comment by Diphen-Hydramine** [comment]
بعد از اینکه کارتون تموم شد آیدیتون رو پاک کنید

**Comment by Shahnamakviko** [comment]
> بعد از اینکه کارتون تموم شد آیدیتون رو پاک کنید

چشم ممنونم از کمک و محبت شما

**Comment by Shahnamakviko** [comment]
> من کمک میکنم

اگر احیانا نتونستی بنده را پیدا کنید آیدی را یک جا در تلگرام کپی و پیست کنید و بر روی آن کلیک کنید

**Comment by tryface1** [comment]
هی بی دلیل اینجا به من اشاره شد؟

**Comment by Shahnamakviko** [comment]
> هی بی دلیل اینجا به من اشاره شد؟

دوست عزیز آیدی بنده در تلگرام آیدی شما در جیت هابه😂

**Comment by tryface1** [comment]
نه، من کاری به آن ندارم، این اکانت برای هیچ چیز استفاده نشده است. برای برقراری ارتباط از مترجم هم استفاده می کنم.

**Comment by Diphen-Hydramine** [comment]
دیروز ورژن v3.0.2 بودیم
الان با آپدیت v3.0.3 دیگه این روش کار‌آمد نیست

**Comment by Diphen-Hydramine** [comment]
داخل #23 صحبت های نهایی راجب این بروزرسانی آخر کاویمو گذاشته شده

**Comment by Shahnamakviko** [comment]
سلام چی شد باز دیگه روش دان که گفتی نمیشه؟
