### ISSUE TITLE
دانلود نمیکنه از ماز

### ISSUE THREAD

**Issue by lamirsk** [Diphen-Hydramine/kavimo-download#3]
از ماز که میزنم اولش دان میشه بعدش ارور میده
thread 'tokio-runtime-worker' panicked at src\video\mod.rs:320:78:
called `Result::unwrap()` on an `Err` value: UnpadError
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
این ارور

**Comment by Diphen-Hydramine** [comment]
I'll answer in #4

**Comment by lamirsk** [comment]
Hello brother, if you can send a message to my telegram, if you want to be paid for this search, can you make someone for us, and it is very important for us to broadcast the classes, we can't download them, I think don't publish this time, or I will pay for anything, if you can, send me a message @NaiaPv ID I left it here so no one else can see it
