### ISSUE TITLE
select quality in batch download

### ISSUE THREAD

**Issue by danialz84** [Diphen-Hydramine/kavimo-download#5]
Is it possible to choose the quality for batch download? For example, write quality in front of the link

**Comment by FarzadAT** [comment]
there is a possibility that the chosen quality might not be available how would you choose to handle that ?

**Comment by Diphen-Hydramine** [comment]
technically yes
but what would happen if the specified quality is unavailable ?

**Comment by Diphen-Hydramine** [comment]
Any further opinions on this one ?

**Comment by danialz84** [comment]
The quality of every movie in the player is known
You also put 0 for the highest quality and 4 for the lowest quality respectively
Well, those who want to download should write the link with / quality at the end
For example, the highest quality of a movie is 1080p and it should be downloaded with the number 0
Now someone wants to download it in 720p
https://stream.biomaze.ir/h43jixcbmhvd/iframe/1

**Comment by Diphen-Hydramine** [comment]
I'd say index based selection is too confusing for this scenario. (Imagine explaining zero based indexing to someone that's just not interested in the topic)
I will implement it with the below syntax:
`<link> <quality>`
`https://stream.biomaze.ir/h43jixcbmhvd/iframe 720`

If the specified quality is not present then the download is aborted

**Comment by mohammadqwerty-asd** [comment]
> من می توانم بگویم انتخاب بر اساس شاخص برای این سناریو خیلی گیج کننده است. (تصور کنید که نمایه سازی مبتنی بر صفر را برای کسی توضیح دهید که علاقه ای به موضوع ندارد) من آن را با نحو زیر پیاده سازی می کنم: `<link> <quality>` `https://stream.biomaze.ir/h43jixcbmhvd/iframe 720`
> 
> اگر کیفیت مشخص شده وجود نداشته باشد، دانلود متوقف می شود


یعنی برنامه را به این صورت آپدیت میکنید درسته؟
من یک پیشنهاد دارم
کلا اگر کیفیت را مشخص نکنیم به این معنی باشه که بالاترین کیفیت منظور هست
مثل الان که هست
ولی من که دارم استفاده میکنم
یک پیشنهاد بود برای کسایی که بعدا به این برنامه نیاز پیدا میکنن و دوست دارن فیلم هاشون بالاترین کیفیت باشه

**Comment by Diphen-Hydramine** [comment]
I consider this one completed
