### ISSUE TITLE
 دانلود دسته ای

### ISSUE THREAD

**Issue by mohammadqwerty-asd** [Diphen-Hydramine/kavimo-download#6]
سلام
من نمیدونم چطور از دانلود دسته‌ای استفاده کنم
و اصلا نمیدونم چی هست
لطفا کمکم کنید

**Comment by lamirsk** [comment]
اول لینک اونایی که میخوای دانلود کنی رو توی فایل txt بزار
بد برو cmd رو توی همون پوشه باز کن و این دستور رو بنویس kavimo-download.exe --file example-batch-file.txt
جای example-batch-file هم اسم فایلتو بنویس

**Comment by mohammadqwerty-asd** [comment]
> اول لینک اونایی که میخوای دانلود کنی رو توی فایل txt بزار بد برو cmd رو توی همون پوشه باز کن و این دستور رو بنویس kavimo-download.exe --file example-batch-file.txt جای example-batch-file هم اسم فایلتو بنویس


نشد نمیدونم کجای کار ایراد داره

**Comment by mohammadqwerty-asd** [comment]
Diphen_Hydramine شما میگید چطور هست؟
ممنون

**Comment by mohammadqwerty-asd** [comment]
دمت گرم جواب داد
همون حرف دوستمون هم درست بود
مشکل کار من بود
من powershell رو باز میکردم
cmd که باز کردم درست شد
دستتون دردنکنه
فقط این کیفیتش روی عدد 3 تنظیم شده
چطور تغییرش بدم

**Comment by Diphen-Hydramine** [comment]
کیفیت دانلود دسته ای همیشه روی بهترین کیفیت موجود هست و قابل انتخاب نیست
دلیلش هم اینه که هنوز راهی به ذهنمون نرسیده اگر کیفیت انتخاب شده وجود نداشته باشه چیکار بکنیم

**Comment by mohammadqwerty-asd** [comment]
دمتون گرم
خیلی برنامه خوبیه
با این دانلود دسته ای هم عالیتر شده
