### ISSUE TITLE
tokio-runtime-worker panicked at src\video\mod.rs:365:52:

### ISSUE THREAD

**Issue by Bee-7** [Diphen-Hydramine/kavimo-download#9]
hey there , first of all appreciated for your project
i got an error while i download a video , this error happens just once on a single video , ( never seen on 133 downloads )
this is the issue
```
[Progress] Key uri reponse code: '200 OK'
thread 'tokio-runtime-worker' panicked at src\video\mod.rs:365:52:
called `Result::unwrap()` on an `Err` value: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Diphen-Hydramine** [comment]
Hi

can you please provide the video link here for further investigation

**Comment by Diphen-Hydramine** [comment]
I'll be closing this.
If you kept getting the error reopen it

**Comment by Bee-7** [comment]
sorry mate , i was away from the internet for some reason so sorry for being late.
this is the link https://stream.oxycapitals.com/mnirmn9nkdy6

**Comment by Diphen-Hydramine** [comment]
new [v1.3.1](https://github.com/Diphen-Hydramine/kavimo-download/releases/download/v1.3.1/kavimo-download.exe) seems to do the job

**Comment by Bee-7** [comment]
> new [v1.3.1](https://github.com/Diphen-Hydramine/kavimo-download/releases/download/v1.3.1/kavimo-download.exe) seems to do the job

خیلی ممنون مشکل حل شده با ورژن جدید
